export const ALL_FEATURES = [
  {
    id: 0,
    label: 'Understand Voter Behaviour',
    features: [
      'Find out from voter behavior which party the voter belongs to ',
      'Convert voters of other parties your voters',
    ],
  },
  {
    id: 1,
    label: 'Voter Management System',
    features: ['Voter Registration',
     'Voter Slip Sharing', 
     'Voter Refferal', 
     'Finding out who voted and who didn’t vote',
     'Role management',
     'Volunteer & Sub-volunteer Management',
     'Candidate Registration',
     'Reminder for vote',
     'Push reminder ( pop-up )',
     ' WhatsApp reminder',
     'Call reminder',
     'Sms reminder',
     'Two-factor Authentication via OTP',
     'weighted voting-taken booth by booth agent',
     'Direct vote appeal to voter by candidate managed by Sub-volunteer & volunteer',
    ],
  },
  {
    id: 2,
    label: 'Stop Fake Voting',
    features: [
      'Real-time fake voting tracking ',
      'Find out where you are leading and lagging behind',
    ],
  },
  {
    id: 3,
    label: 'Social Media Support',
    features: [
      'Digital Group Campaigning',
      'Social Media Managing',
      'Chat Bot',
      'Two Way Communication (with photo and video file uploading features)',
      'Inbuilt dedicated only for election groups like WhatsApp',
      'Party Banner & Logo Design',
      'Template for voter appeal',
      'Template for broadcasting',
      'Template for work assigned to different team members based on their role',
      'Template for food & beverage distribution with menu',
      'Template for Ballot paper', 
    ],
  },
  {
    id: 4,
    label: 'TMS(Transport Management)',
    features: [
      'Onboarding - Offboarding ',
      'Real Time Vehicle Tracking',
      'Fuel Management',
      'Vendor Management',
      'Rent Management',
    ],
  },
  {
    id: 5,
    label: 'EMS(Expense Management System)',
    features: [
      'Food Management',
      'Fuel Management',
      'Gift And Voucher Management',
    ],
  },
];


export const CUSTOM_FEATURES = [
  {
    id: 0,
    label: 'Understand Voter Behaviour',
    features: [
      'Find out from voter behavior which party the voter belongs to ',
      'Convert voters of other parties your voters',
    ],
  },
  {
    id: 1,
    label: 'Voter Management System',
    features: ['Voter Registration',
     'Voter Slip Sharing', 
     'Voter Refferal', 
     'Finding out who voted and who didn’t vote',
     'Role management',
     'Volunteer & Sub-volunteer Management',
     'Candidate Registration',
     'Reminder for vote',
     'Push reminder ( pop-up )',
     ' WhatsApp reminder',
     'Call reminder',
     'Sms reminder',
     'Two-factor Authentication via OTP',
     'weighted voting-taken booth by booth agent',
     'Direct vote appeal to voter by candidate managed by Sub-volunteer & volunteer',
    ],
  },
  {
    id: 2,
    label: 'Stop Fake Voting',
    features: [
      'Real-time fake voting tracking ',
      'Find out where you are leading and lagging behind',
    ],
  },
  {
    id: 3,
    label: 'Social Media Support',
    features: [
      'Digital Group Campaigning',
      'Social Media Managing',
      'Chat Bot',
      'Two Way Communication (with photo and video file uploading features)',
      'Inbuilt dedicated only for election groups like WhatsApp',
      'Party Banner & Logo Design',
      'Template for voter appeal',
      'Template for broadcasting',
      'Template for work assigned to different team members based on their role',
      'Template for food & beverage distribution with menu',
      'Template for Ballot paper', 
    ],
  },
  {
    id: 4,
    label: 'TMS(Transport Management)',
    features: [
      'Onboarding - Offboarding ',
      'Real Time Vehicle Tracking',
      'Fuel Management',
      'Vendor Management',
      'Rent Management',
    ],
  },
  {
    id: 5,
    label: 'EMS(Expense Management System)',
    features: [
      'Food Management',
      'Fuel Management',
      'Gift And Voucher Management',
    ],
  },
];

export const BASIC_FEATURES = [
  {
    id: 0,
    label: 'EMS(Expense Management System)',
    features: [
      'Food Management',
      'Fuel Management',
      'Gift And Voucher Management',
    ],
  },
  {
    id: 1,
    label: 'Social Media Support',
    features: [
      'Digital Group Campaigning',
      'Social Media Managing',
      'Chat Bot',
      'Two Way Communication (with photo and video file uploading features)',
      'Inbuilt dedicated only for election groups like WhatsApp',
      'Party Banner & Logo Design',
      'Template for voter appeal',
      'Template for broadcasting',
      'Template for work assigned to different team members based on their role',
      'Template for food & beverage distribution with menu',
      'Template for Ballot paper',
    ],
  },
  {
    id: 2,
    label: 'TMS(Transport Management)',
    features: [
      'Onboarding - Offboarding ',
      'Real Time Vehicle',
      'Fuel Management',
      'Vendor Management',
      'Rent Management',
    ],
  },
  {
    id: 3,
    label: 'Voter Management System',
    features: ['Voter Registration', 
    'Voter Slip Sharing', 
    'Voter Refferal', 
    'Finding out who voted and who didn’t vote',
    'Role management',
    'Volunteer & Sub-volunteer Management',
    'Candidate Registration',
    'Reminder for vote',
    'Push reminder ( pop-up )',
    ' WhatsApp reminder',
    'Call reminder',
    'Sms reminder',
    'Two-factor Authentication via OTP',
    'weighted voting-taken booth by booth agent',
    'Direct vote appeal to voter by candidate managed by Sub-volunteer & volunteer',
  ],
  },
];
