export const USER_GENDER_OPTIONS = [
  { label: 'MALE', value: 'Male' },
  { label: 'FEMALE', value: 'Female' },
  { label: 'OTHERS', value: 'Others' },
];

export const USER_PARTY_AFFILIATION_OPTIONS = [
  { label: "Bharat Unity Party", value: "Bharat Unity Party" },
  { label: "Jan Shakti Alliance", value: "Jan Shakti Alliance" },
  { label: "Swarajya Party", value: "Swarajya Party" },
  { label: "Samriddhi Sabha", value: "Samriddhi Sabha" },
  { label: "Azaadi Front", value: "Azaadi Front" },
  { label: "Bharatiya Vikas Party", value: "Bharatiya Vikas Party" },
  { label: "Loktantra Sangh", value: "Loktantra Sangh" },
  { label: "Pragati Dal", value: "Pragati Dal" },
  { label: "Samvad Sabha", value: "Samvad Sabha" },
  { label: "Nyay Kranti Party", value: "Nyay Kranti Party" },
  { label: "Hindustan Samarthan Party", value: "Hindustan Samarthan Party" },
  { label: "Rashtriya Vikas Sangathan", value: "Rashtriya Vikas Sangathan" },
  { label: "Bharatiya Nyay Manch", value: "Bharatiya Nyay Manch" },
  { label: "Jantantra Janata Party", value: "Jantantra Janata Party" },
  { label: "Nava Bharat Sangh", value: "Nava Bharat Sangh" },
  { label: "Vikas Ekta Party", value: "Vikas Ekta Party" },
  { label: "Jan Jagran Dal", value: "Jan Jagran Dal" },
  { label: "Aam Aadmi Sangh", value: "Aam Aadmi Sangh" },
  { label: "Pragatisheel Rashtriya Dal", value: "Pragatisheel Rashtriya Dal" },
  { label: "Lok Chetna Sabha", value: "Lok Chetna Sabha" }
];


export const USER_NATIONALITY_OPTIONS = [
  { value: 'Afghan', label: 'Afghan' },
  { value: 'Armenian', label: 'Armenian' },
  { value: 'Azerbaijani', label: 'Azerbaijani' },
  { value: 'Bahraini', label: 'Bahraini' },
  { value: 'Bangladeshi', label: 'Bangladeshi' },
  { value: 'Bhutanese', label: 'Bhutanese' },
  { value: 'Bruneian', label: 'Bruneian' },
  { value: 'Cambodian', label: 'Cambodian' },
  { value: 'Chinese', label: 'Chinese' },
  { value: 'Emirati', label: 'Emirati' },
  { value: 'Filipino', label: 'Filipino' },
  { value: 'Georgian', label: 'Georgian' },
  { value: 'Indian', label: 'Indian' },
  { value: 'Indonesian', label: 'Indonesian' },
  { value: 'Iranian', label: 'Iranian' },
  { value: 'Iraqi', label: 'Iraqi' },
  { value: 'Israeli', label: 'Israeli' },
  { value: 'Japanese', label: 'Japanese' },
  { value: 'Jordanian', label: 'Jordanian' },
  { value: 'Kazakhstani', label: 'Kazakhstani' },
  { value: 'Kuwaiti', label: 'Kuwaiti' },
  { value: 'Kyrgyzstani', label: 'Kyrgyzstani' },
  { value: 'Laotian', label: 'Laotian' },
  { value: 'Lebanese', label: 'Lebanese' },
  { value: 'Malaysian', label: 'Malaysian' },
  { value: 'Maldivian', label: 'Maldivian' },
  { value: 'Mongolian', label: 'Mongolian' },
  { value: 'Nepalese', label: 'Nepalese' },
  { value: 'North Korean', label: 'North Korean' },
  { value: 'Omani', label: 'Omani' },
  { value: 'Pakistani', label: 'Pakistani' },
  { value: 'Palestinian', label: 'Palestinian' },
  { value: 'Qatari', label: 'Qatari' },
  { value: 'Russian', label: 'Russian' },
  { value: 'Saudi Arabian', label: 'Saudi Arabian' },
  { value: 'Singaporean', label: 'Singaporean' },
  { value: 'South Korean', label: 'South Korean' },
  { value: 'Sri Lankan', label: 'Sri Lankan' },
  { value: 'Syrian', label: 'Syrian' },
  { value: 'Taiwanese', label: 'Taiwanese' },
  { value: 'Tajikistani', label: 'Tajikistani' },
  { value: 'Thai', label: 'Thai' },
  { value: 'Timorese', label: 'Timorese' },
  { value: 'Turkish', label: 'Turkish' },
  { value: 'Turkmen', label: 'Turkmen' },
  { value: 'Uzbekistani', label: 'Uzbekistani' },
  { value: 'Vietnamese', label: 'Vietnamese' },
  { value: 'Yemeni', label: 'Yemeni' }
];
export const USER_HIGHEST_QUALIFICATION_OPTIONS = [
  { value: 'High School Diploma', label: 'High School Diploma' },
  { value: 'Associate Degree', label: 'Associate Degree' },
  { value: "Bachelor's Degree", label: "Bachelor's Degree" },
  { value: "Master's Degree", label: "Master's Degree" },
  { value: 'Doctorate (Ph.D.)', label: 'Doctorate (Ph.D.)' },
  { value: 'Professional Degree', label: 'Professional Degree' },
  { value: 'Vocational Degree/Certificate', label: 'Vocational Degree/Certificate' },
  { value: 'Diploma', label: 'Diploma' },
  { value: 'Postdoctoral Degree', label: 'Postdoctoral Degree' },
  { value: 'Honorary Degree', label: 'Honorary Degree' },
  { value: 'No Education', label: 'No Education' },
];

export const USER_IDENTITY_OPTIONS = [
  { label: 'AADHAAR', value: 'Aadhaar' },
  { label: 'PAN', value: 'Pan' },
  { label: 'VOTER', value: 'Voter' },
  { label: 'PASSPORT', value: 'PassPort' },
];

export const USER_STATE_OPTIONS = [
  { label: 'Andaman and Nicobar Islands', value: 'Andaman and Nicobar Islands' },
  { label: 'Andhra Pradesh', value: 'Andhra Pradesh' },
  { label: 'Arunachal Pradesh', value: 'Arunachal Pradesh' },
  { label: 'Assam', value: 'Assam' },
  { label: 'Bihar', value: 'Bihar' },
  { label: 'Chandigarh', value: 'Chandigarh' },
  { label: 'Chhattisgarh', value: 'Chhattisgarh' },
  {
    label: 'Dadra and Nagar Haveli and Daman and Diu',
    value: 'Dadra and Nagar Haveli and Daman and Diu',
  },
  { label: 'Delhi', value: 'Delhi' },
  { label: 'Goa', value: 'Goa' },
  { label: 'Gujarat', value: 'Gujarat' },
  { label: 'Haryana', value: 'Haryana' },
  { label: 'Himachal Pradesh', value: 'Himachal Pradesh' },
  { label: 'Jammu and Kashmir', value: 'Jammu and Kashmir' },
  { label: 'Jharkhand', value: 'Jharkhand' },
  { label: 'Karnataka', value: 'Karnataka' },
  { label: 'Kerala', value: 'Kerala' },
  { label: 'Ladakh', value: 'Ladakh' },
  { label: 'Lakshadweep', value: 'Lakshadweep' },
  { label: 'Madhya Pradesh', value: 'Madhya Pradesh' },
  { label: 'Maharashtra', value: 'Maharashtra' },
  { label: 'Manipur', value: 'Manipur' },
  { label: 'Meghalaya', value: 'Meghalaya' },
  { label: 'Mizoram', value: 'Mizoram' },
  { label: 'Nagaland', value: 'Nagaland' },
  { label: 'Odisha', value: 'Odisha' },
  { label: 'Puducherry', value: 'Puducherry' },
  { label: 'Punjab', value: 'Punjab' },
  { label: 'Rajasthan', value: 'Rajasthan' },
  { label: 'Sikkim', value: 'Sikkim' },
  { label: 'Tamil Nadu', value: 'Tamil Nadu' },
  { label: 'Telangana', value: 'Telangana' },
  { label: 'Tripura', value: 'Tripura' },
  { label: 'Uttar Pradesh', value: 'Uttar Pradesh' },
  { label: 'Uttarakhand', value: 'Uttarakhand' },
  { label: 'West Bengal', value: 'West Bengal' },
];

export const USER_ADDRESS_TYPE_OPTIONS = [
  { label: 'RESIDENTIAL', value: 'Residential' },
  { label: 'HOME', value: 'Home' },
];
