// ----------------------------------------------------------------------

export const WARD_COLOR_OPTIONS = [
  '#00AB55',
  '#000000',
  '#FFFFFF',
  '#FFC0CB',
  '#FF4842',
  '#1890FF',
  '#94D82D',
  '#FFC107',
];

export const WARD_STATES = [
  { value: 'andhra pradesh', label: 'Andhra Pradesh' },
  { value: 'arunachal pradesh', label: 'Arunachal Pradesh' },
  { value: 'assam', label: 'Assam' },
  { value: 'bihar', label: 'Bihar' },
  { value: 'chhattisgarh', label: 'Chhattisgarh' },
  { value: 'goa', label: 'Goa' },
  { value: 'gujarat', label: 'Gujarat' },
  { value: 'haryana', label: 'Haryana' },
  { value: 'himachal pradesh', label: 'Himachal Pradesh' },
  { value: 'jammu and kashmir', label: 'Jammu and Kashmir' },
  { value: 'jharkhand', label: 'Jharkhand' },
  { value: 'karnataka', label: 'Karnataka' },
  { value: 'kerala', label: 'Kerala' },
  { value: 'madhya pradesh', label: 'Madhya Pradesh' },
  { value: 'maharashtra', label: 'Maharashtra' },
  { value: 'manipur', label: 'Manipur' },
  { value: 'meghalaya', label: 'Meghalaya' },
  { value: 'mizoram', label: 'Mizoram' },
  { value: 'nagaland', label: 'Nagaland' },
  { value: 'odisha', label: 'Odisha' },
  { value: 'punjab', label: 'Punjab' },
  { value: 'rajasthan', label: 'Rajasthan' },
  { value: 'sikkim', label: 'Sikkim' },
  { value: 'tamil nadu', label: 'Tamil Nadu' },
  { value: 'telangana', label: 'Telangana' },
  { value: 'tripura', label: 'Tripura' },
  { value: 'uttar pradesh', label: 'Uttar Pradesh' },
  { value: 'uttarakhand', label: 'Uttarakhand' },
  { value: 'west bengal', label: 'West Bengal' },
  { value: 'andaman and nicobar islands', label: 'Andaman and Nicobar Islands' },
  { value: 'chandigarh', label: 'Chandigarh' },
  {
    value: 'dadra and nagar haveli and daman and diu',
    label: 'Dadra and Nagar Haveli and Daman and Diu',
  },
  { value: 'delhi', label: 'Delhi' },
  { value: 'lakshadweep', label: 'Lakshadweep' },
  { value: 'puducherry', label: 'Puducherry' },
];

export const WARD_COUNTRY = [
  { value: 'india', label: 'INDIA' },
  { value: 'afghanistan', label: 'AFGHANISTAN' },
  { value: 'armenia', label: 'ARMENIA' },
  { value: 'azerbaijan', label: 'AZERBAIJAN' },
  { value: 'bahrain', label: 'BAHRAIN' },
  { value: 'bangladesh', label: 'BANGLADESH' },
  { value: 'bhutan', label: 'BHUTAN' },
  { value: 'brunei', label: 'BRUNEI' },
  { value: 'cambodia', label: 'CAMBODIA' },
  { value: 'china', label: 'CHINA' },
  { value: 'cyprus', label: 'CYPRUS' },
  { value: 'georgia', label: 'GEORGIA' },
  { value: 'indonesia', label: 'INDONESIA' },
  { value: 'iran', label: 'IRAN' },
  { value: 'iraq', label: 'IRAQ' },
  { value: 'israel', label: 'ISRAEL' },
  { value: 'japan', label: 'JAPAN' },
  { value: 'jordan', label: 'JORDAN' },
  { value: 'kazakhstan', label: 'KAZAKHSTAN' },
  { value: 'kuwait', label: 'KUWAIT' },
  { value: 'kyrgyzstan', label: 'KYRGYZSTAN' },
  { value: 'laos', label: 'LAOS' },
  { value: 'lebanon', label: 'LEBANON' },
  { value: 'malaysia', label: 'MALAYSIA' },
  { value: 'maldives', label: 'MALDIVES' },
  { value: 'mongolia', label: 'MONGOLIA' },
  { value: 'myanmar', label: 'MYANMAR' },
  { value: 'nepal', label: 'NEPAL' },
  { value: 'north korea', label: 'NORTH KOREA' },
  { value: 'oman', label: 'OMAN' },
  { value: 'pakistan', label: 'PAKISTAN' },
  { value: 'palestine', label: 'PALESTINE' },
  { value: 'philippines', label: 'PHILIPPINES' },
  { value: 'qatar', label: 'QATAR' },
  { value: 'saudi arabia', label: 'SAUDI ARABIA' },
  { value: 'singapore', label: 'SINGAPORE' },
  { value: 'south korea', label: 'SOUTH KOREA' },
  { value: 'sri lanka', label: 'SRI LANKA' },
  { value: 'syria', label: 'SYRIA' },
  { value: 'taiwan', label: 'TAIWAN' },
  { value: 'tajikistan', label: 'TAJIKISTAN' },
  { value: 'thailand', label: 'THAILAND' },
  { value: 'timor-leste', label: 'TIMOR-LESTE' },
  { value: 'turkey', label: 'TURKEY' },
  { value: 'turkmenistan', label: 'TURKMENISTAN' },
  { value: 'united arab emirates', label: 'UNITED ARAB EMIRATES' },
  { value: 'uzbekistan', label: 'UZBEKISTAN' },
  { value: 'vietnam', label: 'VIETNAM' },
  { value: 'yemen', label: 'YEMEN' },
];

export const WARD_LEGAL_CASE_OPTIONS = [
  { value: '0', label: '0' },
  { value: '1', label: '1' },
  { value: '2', label: '2' },
  { value: '3', label: '3' },
  { value: '4', label: '4' },
  { value: '5', label: '5' },
  { value: '6', label: '6' },
  { value: '7', label: '7' },
  { value: '8', label: '8' },
  { value: '9', label: '9' },
  { value: '10', label: '10' },
];
export const WARD_CAPACITY = [
  { value: '500', label: '500' },
  { value: '1000', label: '1000' },
  { value: '2000', label: '2000' },
  { value: '3000', label: '3000' },
  { value: '4000', label: '4000' },
  { value: '5000', label: '5000' },
  { value: '6000', label: '6000' },
  { value: '7000', label: '7000' },
  { value: '8000', label: '8000' },
  { value: '9000', label: '9000' },
  { value: '10000', label: '10000' },
];
export const WARD_PUBLISH_OPTIONS = [
  {
    value: 'published',
    label: 'Published',
  },
  {
    value: 'draft',
    label: 'Draft',
  },
];

export const WARD_CATEGORY_GROUP_OPTIONS = [
  {
    group: 'Clothing',
    classify: ['Shirts', 'T-shirts', 'Jeans', 'Leather', 'Accessories'],
  },
  {
    group: 'Tailored',
    classify: ['Suits', 'Blazers', 'Trousers', 'Waistcoats', 'Apparel'],
  },
  {
    group: 'Accessories',
    classify: ['Shoes', 'Backpacks and bags', 'Bracelets', 'Face masks'],
  },
];

export const WARD_CHECKOUT_STEPS = ['Cart', 'Billing & address', 'Payment'];
